version: '3.7'
services:
  front:
    build:
      context: .
      args:
        CONTAINER_PORT: $CONTAINER_PORT
        HOME_DIR: $HOME_DIR/front
    command: yarn run dev
    volumes:
      - ./front/:/usr/src/front/
    ports:
      - "$FRONT_PORT:$CONTAINER_PORT"
    container_name: blog_nuxt

